version: "3"
services:
#  consul:
#    image: consul:latest
#    container_name: "consul"
#    hostname: consul
#    ports:
#      - "8500:8500"
#      - "8600:8600/udp"
#    command: consul agent -dev -client=0.0.0.0

  zookeeper:
    image: confluentinc/cp-zookeeper:${CP_ZOOKEEPER}
    hostname: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:${CP_KAFKA}
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  redis:
    image: bitnami/redis:5.0.7
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"

#  App services
  command:
    image: zhenik/tapad1-command:${APP_VERSION}
    build: ./command
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: "timestamp-user-action-v1"
    ports:
    - "8081:8080"
    depends_on:
      - zookeeper
      - kafka

  processor:
    image: zhenik/tapad1-processor:${APP_VERSION}
    build: ./processor
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_INPUT_TOPIC: "timestamp-user-action-v1"
      KAFKA_OUTPUT_TOPIC: "analytics-v1"
    depends_on:
      - zookeeper
      - kafka

  materializer:
    image: zhenik/tapad1-materializer:${APP_VERSION}
    build: ./materializer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_SOURCE_TOPIC: "analytics-v1"
      REDIS_URI: "redis://redis:6379"
    depends_on:
      - zookeeper
      - kafka
      - redis

  query:
    image: zhenik/tapad1-query:${APP_VERSION}
    build: ./query
    environment:
      REDIS_URI: "redis://redis:6379"
      APP_PORT: 8080
    ports:
      - "8082:8080"
    depends_on:
      - redis